import 'controller/date_filter_tab_container_controller.dart';import 'package:ecommerce_seller_app/core/app_export.dart';import 'package:ecommerce_seller_app/presentation/date_filter_one_page/date_filter_one_page.dart';import 'package:ecommerce_seller_app/presentation/date_filter_page/date_filter_page.dart';import 'package:ecommerce_seller_app/presentation/profile_page/profile_page.dart';import 'package:ecommerce_seller_app/presentation/search_package_page/search_package_page.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_leading_iconbutton_one.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_title.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_trailing_iconbutton_two.dart';import 'package:ecommerce_seller_app/widgets/app_bar/custom_app_bar.dart';import 'package:ecommerce_seller_app/widgets/custom_bottom_bar.dart';import 'package:flutter/material.dart';class DateFilterTabContainerScreen extends GetWidget<DateFilterTabContainerController> {const DateFilterTabContainerScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 30.v), Container(decoration: AppDecoration.outlineBlack.copyWith(borderRadius: BorderRadiusStyle.customBorderBL38), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 31.v, width: 297.h, child: TabBar(controller: controller.tabviewController, labelPadding: EdgeInsets.zero, labelColor: appTheme.whiteA700, labelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w400), unselectedLabelColor: theme.colorScheme.primaryContainer.withOpacity(1), unselectedLabelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w400), indicator: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(5.h)), tabs: [Tab(child: Text("lbl_all".tr)), Tab(child: Text("lbl_todays".tr)), Tab(child: Text("lbl_date".tr))])), SizedBox(height: 560.v, child: TabBarView(controller: controller.tabviewController, children: [DateFilterPage(), DateFilterPage(), DateFilterOnePage()]))]))])), bottomNavigationBar: _buildBottomBar())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 57.h, leading: AppbarLeadingIconbuttonOne(imagePath: ImageConstant.imgFilter1Primarycontainer, margin: EdgeInsets.only(left: 25.h, top: 12.v, bottom: 12.v), onTap: () {onTapFilterOne();}), centerTitle: true, title: AppbarTitle(text: "lbl_selling_record".tr), actions: [AppbarTrailingIconbuttonTwo(imagePath: ImageConstant.imgCalendar1Black900, margin: EdgeInsets.symmetric(horizontal: 25.h, vertical: 12.v))]); } 
/// Section Widget
Widget _buildBottomBar() { return CustomBottomBar(onChanged: (BottomBarEnum type) {Get.toNamed(getCurrentRoute(type), id: 1);}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Add11: return AppRoutes.searchPackagePage; case BottomBarEnum.Add2: return "/"; case BottomBarEnum.Checklist2: return "/"; case BottomBarEnum.Search: return "/"; case BottomBarEnum.Framebluegray4000220x20: return AppRoutes.profilePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.searchPackagePage: return SearchPackagePage(); case AppRoutes.profilePage: return ProfilePage(); default: return DefaultWidget();} } 
/// Navigates to the orderFilterScreen when the action is triggered.
onTapFilterOne() { Get.toNamed(AppRoutes.orderFilterScreen, ); } 
 }
