import '../delivery_in_queue_one_screen/widgets/orderdetails_item_widget.dart';import 'controller/delivery_in_queue_one_controller.dart';import 'models/orderdetails_item_model.dart';import 'package:ecommerce_seller_app/core/app_export.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_leading_iconbutton_one.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_title.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_trailing_iconbutton_two.dart';import 'package:ecommerce_seller_app/widgets/app_bar/custom_app_bar.dart';import 'package:ecommerce_seller_app/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';class DeliveryInQueueOneScreen extends GetWidget<DeliveryInQueueOneController> {const DeliveryInQueueOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 2.v), child: Column(children: [_buildInQueue(), SizedBox(height: 15.v), SizedBox(height: 960.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [_buildEightySeven(), _buildOrderDetails()])), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 57.h, leading: AppbarLeadingIconbuttonOne(imagePath: ImageConstant.imgFilter1Primarycontainer, margin: EdgeInsets.only(left: 25.h, top: 12.v, bottom: 12.v), onTap: () {onTapFilterOne();}), centerTitle: true, title: AppbarTitle(text: "msg_today_s_delivery".tr), actions: [AppbarTrailingIconbuttonTwo(imagePath: ImageConstant.imgCalendar1Black900, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 12.v))]); } 
/// Section Widget
Widget _buildInQueue() { return Padding(padding: EdgeInsets.symmetric(horizontal: 25.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_in_queue".tr, style: theme.textTheme.titleMedium), Padding(padding: EdgeInsets.only(left: 6.h, bottom: 4.v), child: Text("lbl_2000_items2".tr, style: CustomTextStyles.bodySmallSecondaryContainer)), Spacer(), Container(width: 50.h, margin: EdgeInsets.only(top: 3.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(right: 5.h), child: CustomIconButton(height: 20.adaptSize, width: 20.adaptSize, padding: EdgeInsets.all(4.h), decoration: IconButtonStyleHelper.fillGray1, onTap: () {onTapBtnIconButton();}, child: CustomImageView(imagePath: ImageConstant.imgFrameGray60001)))), Expanded(child: Padding(padding: EdgeInsets.only(left: 5.h), child: CustomIconButton(height: 20.adaptSize, width: 20.adaptSize, child: CustomImageView(imagePath: ImageConstant.imgMenuGray900))))]))])); } 
/// Section Widget
Widget _buildEightySeven() { return Align(alignment: Alignment.bottomCenter, child: Container(margin: EdgeInsets.only(bottom: 240.v), padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 11.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("msg_order_id_aa4587v".tr, style: CustomTextStyles.titleSmallGray40001), Padding(padding: EdgeInsets.only(top: 4.v), child: Text("msg_status_in_queue".tr, style: CustomTextStyles.bodySmallRed300))]), SizedBox(height: 6.v), Text("msg_electric_package".tr, style: CustomTextStyles.titleSmallGray900), SizedBox(height: 2.v), RichText(text: TextSpan(children: [TextSpan(text: "lbl_address".tr, style: CustomTextStyles.bodySmall11), TextSpan(text: "msg_42_5_malibagh_moor".tr, style: CustomTextStyles.bodySmallGray60001)]), textAlign: TextAlign.left), SizedBox(height: 4.v), Text("lbl_50_00".tr, style: CustomTextStyles.titleSmallRed300), SizedBox(height: 2.v)]))); } 
/// Section Widget
Widget _buildOrderDetails() { return Align(alignment: Alignment.center, child: Obx(() => ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 1.v);}, itemCount: controller.deliveryInQueueOneModelObj.value.orderdetailsItemList.value.length, itemBuilder: (context, index) {OrderdetailsItemModel model = controller.deliveryInQueueOneModelObj.value.orderdetailsItemList.value[index]; return OrderdetailsItemWidget(model);}))); } 
/// Navigates to the orderFilterScreen when the action is triggered.
onTapFilterOne() { Get.toNamed(AppRoutes.orderFilterScreen, ); } 
/// Navigates to the deliveryInQueueScreen when the action is triggered.
onTapBtnIconButton() { Get.toNamed(AppRoutes.deliveryInQueueScreen, ); } 
 }
