import '../category_four_screen/widgets/mobiletextlist1_item_widget.dart';import '../category_four_screen/widgets/productcard3_item_widget.dart';import 'controller/category_four_controller.dart';import 'models/mobiletextlist1_item_model.dart';import 'models/productcard3_item_model.dart';import 'package:ecommerce_seller_app/core/app_export.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_title.dart';import 'package:ecommerce_seller_app/widgets/app_bar/custom_app_bar.dart';import 'package:ecommerce_seller_app/widgets/custom_elevated_button.dart';import 'package:ecommerce_seller_app/widgets/custom_icon_button.dart';import 'package:ecommerce_seller_app/widgets/custom_search_view.dart';import 'package:flutter/material.dart';class CategoryFourScreen extends GetWidget<CategoryFourController> {const CategoryFourScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 5.v), child: Column(children: [SizedBox(height: 13.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(bottom: 5.v), child: Column(children: [_buildMenuRow(), SizedBox(height: 18.v), _buildMobileTextList(), SizedBox(height: 16.v), _buildButtonTextColumn(), SizedBox(height: 15.v), _buildGroceriesRow(), SizedBox(height: 16.v), _buildHomeDCorRow(), SizedBox(height: 16.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: _buildFashionRow2(fashionText: "lbl_fashion".tr, itemsText: "lbl_2000_items".tr)), SizedBox(height: 16.v), _buildFashionRow(), SizedBox(height: 16.v), _buildSportsRow(), SizedBox(height: 16.v), _buildMedicineRow()]))))])), bottomNavigationBar: _buildPreview())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 66.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 7.v, bottom: 7.v)), centerTitle: true, title: AppbarTitle(text: "lbl_create_packages".tr)); } 
/// Section Widget
Widget _buildMenuRow() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.symmetric(vertical: 5.v), child: CustomIconButton(height: 42.adaptSize, width: 42.adaptSize, padding: EdgeInsets.all(11.h), child: CustomImageView(imagePath: ImageConstant.imgMenu))), Expanded(child: Padding(padding: EdgeInsets.only(left: 11.h), child: CustomSearchView(controller: controller.searchController, hintText: "lbl_search_product".tr)))])); } 
/// Section Widget
Widget _buildMobileTextList() { return Align(alignment: Alignment.centerLeft, child: SizedBox(height: 57.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(left: 24.h, right: 54.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 20.h);}, itemCount: controller.categoryFourModelObj.value.mobiletextlist1ItemList.value.length, itemBuilder: (context, index) {Mobiletextlist1ItemModel model = controller.categoryFourModelObj.value.mobiletextlist1ItemList.value[index]; return Mobiletextlist1ItemWidget(model);})))); } 
/// Section Widget
Widget _buildSpeaker() { return Container(margin: EdgeInsets.only(left: 4.h), padding: EdgeInsets.symmetric(horizontal: 3.h), child: Column(crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(left: 58.h), child: _buildSpeakerRow(speakerText: "lbl_speaker".tr, arrowImage: ImageConstant.imgArrowRightSecondarycontainer)), SizedBox(height: 7.v), Padding(padding: EdgeInsets.only(left: 58.h), child: _buildSpeakerRow(speakerText: "lbl_accessories".tr, arrowImage: ImageConstant.imgArrowRightSecondarycontainer)), SizedBox(height: 12.v), Padding(padding: EdgeInsets.only(left: 58.h), child: _buildSpeakerRow(speakerText: "lbl_headphone".tr, arrowImage: ImageConstant.imgArrowRightSecondarycontainer)), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(left: 58.h), child: _buildSpeakerRow(speakerText: "lbl_tv".tr, arrowImage: ImageConstant.imgArrowRightSecondarycontainer)), SizedBox(height: 9.v), Padding(padding: EdgeInsets.only(left: 58.h), child: _buildSpeakerRow(speakerText: "lbl_monitor".tr, arrowImage: ImageConstant.imgArrowRightSecondarycontainer))])); } 
/// Section Widget
Widget _buildButtonTextColumn() { return Container(padding: EdgeInsets.symmetric(horizontal: 21.h, vertical: 8.v), decoration: AppDecoration.fillGray, child: Column(children: [Padding(padding: EdgeInsets.only(left: 4.h, right: 3.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgEllipse4, height: 56.adaptSize, width: 56.adaptSize, radius: BorderRadius.circular(28.h)), Padding(padding: EdgeInsets.only(left: 15.h, bottom: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_electronics".tr, style: theme.textTheme.titleLarge), Text("lbl_2000_items".tr, style: CustomTextStyles.bodySmallSecondaryContainer)])), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 12.v), child: CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.fillBlue, child: CustomImageView(imagePath: ImageConstant.imgArrowUp)))])), SizedBox(height: 12.v), Padding(padding: EdgeInsets.only(left: 65.h, right: 3.h), child: _buildSpeakerRow(speakerText: "lbl_mobile".tr, arrowImage: ImageConstant.imgArrowDownSecondarycontainer)), SizedBox(height: 5.v), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(left: 36.h), child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 18.v);}, itemCount: controller.categoryFourModelObj.value.productcard3ItemList.value.length, itemBuilder: (context, index) {Productcard3ItemModel model = controller.categoryFourModelObj.value.productcard3ItemList.value[index]; return Productcard3ItemWidget(model);})))), SizedBox(height: 33.v), _buildSpeaker(), SizedBox(height: 8.v)])); } 
/// Section Widget
Widget _buildGroceriesRow() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgEllipse456x56, height: 56.adaptSize, width: 56.adaptSize, radius: BorderRadius.circular(28.h)), Padding(padding: EdgeInsets.only(left: 15.h, bottom: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_groceries".tr, style: theme.textTheme.titleLarge), Text("lbl_2000_items".tr, style: CustomTextStyles.bodySmallSecondaryContainer)])), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 12.v), child: CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.fillBlue, child: CustomImageView(imagePath: ImageConstant.imgArrowDown)))])); } 
/// Section Widget
Widget _buildHomeDCorRow() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgEllipse41, height: 56.adaptSize, width: 56.adaptSize, radius: BorderRadius.circular(28.h)), Padding(padding: EdgeInsets.only(left: 15.h, bottom: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_home_d_cor".tr, style: theme.textTheme.titleLarge), Text("lbl_2000_items".tr, style: CustomTextStyles.bodySmallSecondaryContainer)])), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 12.v), child: CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.fillBlue, child: CustomImageView(imagePath: ImageConstant.imgArrowDown)))])); } 
/// Section Widget
Widget _buildFashionRow() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgEllipse43, height: 56.adaptSize, width: 56.adaptSize, radius: BorderRadius.circular(28.h)), Padding(padding: EdgeInsets.only(left: 15.h, top: 3.v, bottom: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_beauty_product".tr, style: theme.textTheme.titleLarge), Text("lbl_2000_items".tr, style: CustomTextStyles.bodySmallSecondaryContainer)])), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 12.v), child: CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.fillBlue, child: CustomImageView(imagePath: ImageConstant.imgArrowDown)))])); } 
/// Section Widget
Widget _buildSportsRow() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgEllipse44, height: 56.adaptSize, width: 56.adaptSize, radius: BorderRadius.circular(28.h)), Padding(padding: EdgeInsets.only(left: 15.h, top: 3.v, bottom: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_sports".tr, style: theme.textTheme.titleLarge), Text("lbl_2000_items".tr, style: CustomTextStyles.bodySmallSecondaryContainer)])), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 12.v), child: CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.fillBlue, child: CustomImageView(imagePath: ImageConstant.imgArrowDown)))])); } 
/// Section Widget
Widget _buildMedicineRow() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgEllipse45, height: 56.adaptSize, width: 56.adaptSize, radius: BorderRadius.circular(28.h)), Padding(padding: EdgeInsets.only(left: 15.h, bottom: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_medicine".tr, style: theme.textTheme.titleLarge), Text("lbl_2000_items".tr, style: CustomTextStyles.bodySmallSecondaryContainer)])), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 12.v), child: CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.fillBlue, child: CustomImageView(imagePath: ImageConstant.imgArrowDown)))])); } 
/// Section Widget
Widget _buildPreviewButton() { return CustomElevatedButton(width: 156.h, text: "lbl_preview".tr, rightIcon: Container(margin: EdgeInsets.only(left: 8.h), child: CustomImageView(imagePath: ImageConstant.imgArrowrightWhiteA700, height: 20.adaptSize, width: 20.adaptSize)), onPressed: () {onTapPreviewButton();}, alignment: Alignment.topRight); } 
/// Section Widget
Widget _buildPreview() { return Container(height: 60.v, width: 326.h, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 5.v), child: Stack(alignment: Alignment.topRight, children: [Padding(padding: EdgeInsets.only(top: 4.v), child: _buildFashionRow2(fashionText: "lbl_fashion".tr, itemsText: "lbl_2000_items".tr)), _buildPreviewButton()])); } 
/// Common widget
Widget _buildSpeakerRow({required String speakerText, required String arrowImage, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(speakerText, style: CustomTextStyles.bodyLargeBlack90016.copyWith(color: appTheme.black900)), CustomImageView(imagePath: arrowImage, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(bottom: 4.v))]); } 
/// Common widget
Widget _buildFashionRow2({required String fashionText, required String itemsText, }) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgEllipse42, height: 56.adaptSize, width: 56.adaptSize, radius: BorderRadius.circular(28.h)), Padding(padding: EdgeInsets.only(left: 15.h, bottom: 7.v), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.center, child: Text(fashionText, style: theme.textTheme.titleLarge!.copyWith(color: theme.colorScheme.primaryContainer.withOpacity(1)))), Text(itemsText, style: CustomTextStyles.bodySmallSecondaryContainer.copyWith(color: theme.colorScheme.secondaryContainer))])), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 12.v), child: CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.fillBlue, child: CustomImageView(imagePath: ImageConstant.imgArrowDown)))]); } 
/// Navigates to the productPublishTwoScreen when the action is triggered.
onTapPreviewButton() { Get.toNamed(AppRoutes.productPublishTwoScreen, ); } 
 }
