import 'controller/home_settings_controller.dart';import 'package:ecommerce_seller_app/core/app_export.dart';import 'package:ecommerce_seller_app/presentation/profile_page/profile_page.dart';import 'package:ecommerce_seller_app/presentation/search_package_page/search_package_page.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_title.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:ecommerce_seller_app/widgets/app_bar/custom_app_bar.dart';import 'package:ecommerce_seller_app/widgets/custom_bottom_bar.dart';import 'package:ecommerce_seller_app/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;class HomeSettingsScreen extends GetWidget<HomeSettingsController> {const HomeSettingsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 27.v), child: Column(children: [_buildWelcomeSection(), SizedBox(height: 20.v), _buildTotalProductsRow(), SizedBox(height: 20.v), _buildAllPackagesRow(), SizedBox(height: 20.v), _buildOrderDetailsRow(), SizedBox(height: 5.v)])), bottomNavigationBar: _buildBottomBar())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(centerTitle: true, title: AppbarTitle(text: "lbl_dashboard".tr), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgNotification, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 7.v), onTap: () {onTapNotification();})]); } 
/// Section Widget
Widget _buildWelcomeSection() { return Container(width: 327.h, padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 6.v), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder20, image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup557), fit: BoxFit.cover)), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [_buildTodaySalesColumn(todaySalesText: "lbl_welcome".tr, priceText: "msg_shopno_wear_house".tr), SizedBox(height: 19.v), _buildTodaySalesColumn(todaySalesText: "lbl_today_s_sales".tr, priceText: "lbl_500_00".tr), SizedBox(height: 15.v)])); } 
/// Section Widget
Widget _buildTotalProductsRow() { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 12.v), decoration: AppDecoration.fillBlue.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 8.h, top: 6.v, bottom: 9.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_total_products".tr, style: CustomTextStyles.titleMediumGray80001), SizedBox(height: 3.v), Text("lbl_total_2035".tr, style: CustomTextStyles.bodyLargeBlack90016)])), Padding(padding: EdgeInsets.only(bottom: 5.v), child: _buildAllPackagesColumn(viewAllText: "lbl_view_all".tr, onTapIconButton: () {onTapIconButton();}, onTapMynauiEdit: () {onTapMynauiEdit();}))])); } 
/// Section Widget
Widget _buildAllPackagesRow() { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 12.v), decoration: AppDecoration.fillCyan.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 8.h, top: 9.v, bottom: 9.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_all_packages".tr, style: CustomTextStyles.titleMediumGray80001), Text("lbl_total_2035".tr, style: CustomTextStyles.bodyLargeBlack90016)])), Padding(padding: EdgeInsets.only(bottom: 5.v), child: _buildAllPackagesColumn(viewAllText: "lbl_view_all".tr, onTapIconButton: () {onTapIconButton1();}, onTapMynauiEdit: () {onTapMynauiEdit1();}))])); } 
/// Section Widget
Widget _buildOrderDetailsRow() { return GestureDetector(onTap: () {onTapOrderDetailsRow();}, child: Container(padding: EdgeInsets.symmetric(horizontal: 21.h, vertical: 33.v), decoration: AppDecoration.fillPink.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(left: 3.h), child: Text("lbl_order_details".tr, style: CustomTextStyles.titleMediumGray80001)), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 4.v), child: Text("lbl_view_details".tr, style: CustomTextStyles.bodySmallPrimaryContainer)), CustomImageView(imagePath: ImageConstant.imgArrowRightBlack900, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 3.h, top: 6.v, bottom: 5.v))]))); } 
/// Section Widget
Widget _buildBottomBar() { return CustomBottomBar(onChanged: (BottomBarEnum type) {Get.toNamed(getCurrentRoute(type), id: 1);}); } 
/// Common widget
Widget _buildTodaySalesColumn({required String todaySalesText, required String priceText, }) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(todaySalesText, style: CustomTextStyles.titleMediumWhiteA700.copyWith(color: appTheme.whiteA700)), Text(priceText, style: CustomTextStyles.titleMediumRed300.copyWith(color: appTheme.red300))]); } 
/// Common widget
Widget _buildAllPackagesColumn({required String viewAllText, Function? onTapIconButton, Function? onTapMynauiEdit, }) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.centerRight, child: Container(width: 62.h, margin: EdgeInsets.only(left: 11.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(right: 7.h), child: CustomIconButton(height: 24.adaptSize, width: 24.adaptSize, padding: EdgeInsets.all(4.h), decoration: IconButtonStyleHelper.fillPrimary, onTap: () {onTapIconButton!.call();}, child: CustomImageView(imagePath: ImageConstant.imgFrameWhiteA700)))), Expanded(child: Padding(padding: EdgeInsets.only(left: 7.h), child: CustomIconButton(height: 24.adaptSize, width: 24.adaptSize, padding: EdgeInsets.all(4.h), decoration: IconButtonStyleHelper.fillPrimary, onTap: () {onTapMynauiEdit!.call();}, child: CustomImageView(imagePath: ImageConstant.imgMynauiEditWhiteA700))))]))), SizedBox(height: 23.v), Row(children: [Text(viewAllText, style: CustomTextStyles.bodySmallPrimaryContainer.copyWith(color: theme.colorScheme.primaryContainer.withOpacity(1))), CustomImageView(imagePath: ImageConstant.imgArrowRightBlack900, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 3.h))])]); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Add11: return AppRoutes.searchPackagePage; case BottomBarEnum.Add2: return "/"; case BottomBarEnum.Checklist2: return "/"; case BottomBarEnum.Search: return "/"; case BottomBarEnum.Framebluegray4000220x20: return AppRoutes.profilePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.searchPackagePage: return SearchPackagePage(); case AppRoutes.profilePage: return ProfilePage(); default: return DefaultWidget();} } 
/// Navigates to the notificationScreen when the action is triggered.
onTapNotification() { Get.toNamed(AppRoutes.notificationScreen, ); } 
/// Navigates to the addProductOneScreen when the action is triggered.
onTapIconButton() { Get.toNamed(AppRoutes.addProductOneScreen, ); } 
/// Navigates to the searchProductScreen when the action is triggered.
onTapMynauiEdit() { Get.toNamed(AppRoutes.searchProductScreen, ); } 
/// Navigates to the createPackageScreen when the action is triggered.
onTapIconButton1() { Get.toNamed(AppRoutes.createPackageScreen, ); } 
/// Navigates to the searchPackageOneScreen when the action is triggered.
onTapMynauiEdit1() { Get.toNamed(AppRoutes.searchPackageOneScreen, ); } 
/// Navigates to the orderDetailsScreen when the action is triggered.
onTapOrderDetailsRow() { Get.toNamed(AppRoutes.orderDetailsScreen, ); } 
 }
