import '../category_two_screen/widgets/mobiletextlist_item_widget.dart';import '../category_two_screen/widgets/productcardlist1_item_widget.dart';import 'controller/category_two_controller.dart';import 'models/mobiletextlist_item_model.dart';import 'models/productcardlist1_item_model.dart';import 'package:ecommerce_seller_app/core/app_export.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_title.dart';import 'package:ecommerce_seller_app/widgets/app_bar/custom_app_bar.dart';import 'package:ecommerce_seller_app/widgets/custom_elevated_button.dart';import 'package:ecommerce_seller_app/widgets/custom_icon_button.dart';import 'package:ecommerce_seller_app/widgets/custom_search_view.dart';import 'package:flutter/material.dart';class CategoryTwoScreen extends GetWidget<CategoryTwoController> {const CategoryTwoScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 25.h, vertical: 13.v), child: Column(children: [_buildMenuRow(), SizedBox(height: 18.v), _buildMobileTextList(), SizedBox(height: 30.v), _buildProductCardList(), SizedBox(height: 42.v), _buildPreviewButton(), SizedBox(height: 9.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 66.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 7.v, bottom: 7.v), onTap: () {onTapArrowDown();}), centerTitle: true, title: AppbarTitle(text: "lbl_create_packages".tr)); } 
/// Section Widget
Widget _buildMenuRow() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.symmetric(vertical: 5.v), child: CustomIconButton(height: 42.adaptSize, width: 42.adaptSize, padding: EdgeInsets.all(11.h), child: CustomImageView(imagePath: ImageConstant.imgMenu))), Expanded(child: Padding(padding: EdgeInsets.only(left: 11.h), child: CustomSearchView(controller: controller.searchController, hintText: "lbl_search_product".tr)))]); } 
/// Section Widget
Widget _buildMobileTextList() { return Align(alignment: Alignment.centerLeft, child: SizedBox(height: 57.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(left: 7.h, right: 21.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 20.h);}, itemCount: controller.categoryTwoModelObj.value.mobiletextlistItemList.value.length, itemBuilder: (context, index) {MobiletextlistItemModel model = controller.categoryTwoModelObj.value.mobiletextlistItemList.value[index]; return MobiletextlistItemWidget(model);})))); } 
/// Section Widget
Widget _buildProductCardList() { return Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 18.v);}, itemCount: controller.categoryTwoModelObj.value.productcardlist1ItemList.value.length, itemBuilder: (context, index) {Productcardlist1ItemModel model = controller.categoryTwoModelObj.value.productcardlist1ItemList.value[index]; return Productcardlist1ItemWidget(model);})); } 
/// Section Widget
Widget _buildPreviewButton() { return CustomElevatedButton(width: 156.h, text: "lbl_preview".tr, rightIcon: Container(margin: EdgeInsets.only(left: 8.h), child: CustomImageView(imagePath: ImageConstant.imgArrowrightWhiteA700, height: 20.adaptSize, width: 20.adaptSize)), onPressed: () {onTapPreviewButton();}, alignment: Alignment.centerRight); } 
/// Navigates to the productListScreen when the action is triggered.
onTapArrowDown() { Get.toNamed(AppRoutes.productListScreen, ); } 
/// Navigates to the productPublishScreen when the action is triggered.
onTapPreviewButton() { Get.toNamed(AppRoutes.productPublishScreen, ); } 
 }
