import 'controller/create_package_controller.dart';import 'package:ecommerce_seller_app/core/app_export.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_title.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_trailing_iconbutton_one.dart';import 'package:ecommerce_seller_app/widgets/app_bar/custom_app_bar.dart';import 'package:ecommerce_seller_app/widgets/custom_icon_button.dart';import 'package:ecommerce_seller_app/widgets/custom_search_view.dart';import 'package:flutter/material.dart';class CreatePackageScreen extends GetWidget<CreatePackageController> {const CreatePackageScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 9.v), child: Column(children: [SizedBox(height: 13.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(bottom: 5.v), child: Column(children: [_buildMenuRow(), SizedBox(height: 30.v), _buildElectronicsRow(), _buildGroceriesRow(), _buildHomeDCorRow(), _buildFashionRow(fashionText: "lbl_fashion".tr, itemsText: "lbl_2000_items".tr), _buildBeautyProductRow(), _buildSportsRow(), _buildMedicineRow(), _buildFashionRow(fashionText: "lbl_fashion".tr, itemsText: "lbl_2000_items".tr)]))))])), bottomNavigationBar: _buildBeautyProductRow1())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 66.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 7.v, bottom: 7.v)), centerTitle: true, title: AppbarTitle(text: "lbl_create_packages".tr), actions: [AppbarTrailingIconbuttonOne(imagePath: ImageConstant.imgMynauiEdit, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 14.v))]); } 
/// Section Widget
Widget _buildMenuRow() { return Padding(padding: EdgeInsets.symmetric(horizontal: 25.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.symmetric(vertical: 5.v), child: CustomIconButton(height: 42.adaptSize, width: 42.adaptSize, padding: EdgeInsets.all(11.h), onTap: () {onTapBtnMenu();}, child: CustomImageView(imagePath: ImageConstant.imgMenu))), Expanded(child: Padding(padding: EdgeInsets.only(left: 11.h), child: CustomSearchView(controller: controller.searchController, hintText: "lbl_search_product".tr)))])); } 
/// Section Widget
Widget _buildElectronicsRow() { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 8.v), decoration: AppDecoration.fillGray, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgEllipse4, height: 56.adaptSize, width: 56.adaptSize, radius: BorderRadius.circular(28.h)), Padding(padding: EdgeInsets.only(left: 15.h, bottom: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_electronics".tr, style: theme.textTheme.titleLarge), Text("lbl_2000_items".tr, style: CustomTextStyles.bodySmallSecondaryContainer)])), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 12.v), child: CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.fillBlue, onTap: () {onTapBtnArrowDown();}, child: CustomImageView(imagePath: ImageConstant.imgArrowDown)))])); } 
/// Section Widget
Widget _buildGroceriesRow() { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 8.v), decoration: AppDecoration.fillWhiteA, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgEllipse456x56, height: 56.adaptSize, width: 56.adaptSize, radius: BorderRadius.circular(28.h)), Padding(padding: EdgeInsets.only(left: 15.h, bottom: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_groceries".tr, style: theme.textTheme.titleLarge), Text("lbl_2000_items".tr, style: CustomTextStyles.bodySmallSecondaryContainer)])), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 12.v), child: CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.fillBlue, child: CustomImageView(imagePath: ImageConstant.imgArrowDown)))])); } 
/// Section Widget
Widget _buildHomeDCorRow() { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 8.v), decoration: AppDecoration.fillGray, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgEllipse41, height: 56.adaptSize, width: 56.adaptSize, radius: BorderRadius.circular(28.h)), Padding(padding: EdgeInsets.only(left: 15.h, bottom: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_home_d_cor".tr, style: theme.textTheme.titleLarge), Text("lbl_2000_items".tr, style: CustomTextStyles.bodySmallSecondaryContainer)])), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 12.v), child: CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.fillBlue, child: CustomImageView(imagePath: ImageConstant.imgArrowDown)))])); } 
/// Section Widget
Widget _buildBeautyProductRow() { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 8.v), decoration: AppDecoration.fillGray, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgEllipse43, height: 56.adaptSize, width: 56.adaptSize, radius: BorderRadius.circular(28.h)), Padding(padding: EdgeInsets.only(left: 15.h, top: 3.v, bottom: 7.v), child: _buildBeautyProductColumn(title: "lbl_beauty_product".tr, subtitle: "lbl_2000_items".tr)), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 12.v), child: CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.fillBlue, child: CustomImageView(imagePath: ImageConstant.imgArrowDown)))])); } 
/// Section Widget
Widget _buildSportsRow() { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 8.v), decoration: AppDecoration.fillWhiteA, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgEllipse44, height: 56.adaptSize, width: 56.adaptSize, radius: BorderRadius.circular(28.h)), Padding(padding: EdgeInsets.only(left: 15.h, top: 3.v, bottom: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_sports".tr, style: theme.textTheme.titleLarge), Text("lbl_2000_items".tr, style: CustomTextStyles.bodySmallSecondaryContainer)])), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 12.v), child: CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.fillBlue, child: CustomImageView(imagePath: ImageConstant.imgArrowDown)))])); } 
/// Section Widget
Widget _buildMedicineRow() { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 8.v), decoration: AppDecoration.fillGray, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgEllipse45, height: 56.adaptSize, width: 56.adaptSize, radius: BorderRadius.circular(28.h)), Padding(padding: EdgeInsets.only(left: 15.h, bottom: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_medicine".tr, style: theme.textTheme.titleLarge), Text("lbl_2000_items".tr, style: CustomTextStyles.bodySmallSecondaryContainer)])), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 12.v), child: CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.fillBlue, child: CustomImageView(imagePath: ImageConstant.imgArrowDown)))])); } 
/// Section Widget
Widget _buildBeautyProductRow1() { return Container(margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 46.v), decoration: AppDecoration.fillGray, child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgEllipse46, height: 56.adaptSize, width: 56.adaptSize, radius: BorderRadius.circular(28.h)), Padding(padding: EdgeInsets.only(left: 15.h, top: 3.v, bottom: 7.v), child: _buildBeautyProductColumn(title: "lbl_beauty_product".tr, subtitle: "lbl_2000_items".tr)), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 12.v), child: CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(4.h), decoration: IconButtonStyleHelper.fillBlue, child: CustomImageView(imagePath: ImageConstant.imgArrowDownPrimarycontainer32x32)))])); } 
/// Common widget
Widget _buildFashionRow({required String fashionText, required String itemsText, }) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 8.v), decoration: AppDecoration.fillWhiteA, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgEllipse42, height: 56.adaptSize, width: 56.adaptSize, radius: BorderRadius.circular(28.h)), Padding(padding: EdgeInsets.only(left: 15.h, bottom: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.center, child: Text(fashionText, style: theme.textTheme.titleLarge!.copyWith(color: theme.colorScheme.primaryContainer.withOpacity(1)))), Text(itemsText, style: CustomTextStyles.bodySmallSecondaryContainer.copyWith(color: theme.colorScheme.secondaryContainer))])), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 12.v), child: CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.fillBlue, child: CustomImageView(imagePath: ImageConstant.imgArrowDown)))])); } 
/// Common widget
Widget _buildBeautyProductColumn({required String title, required String subtitle, }) { return Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text(title, style: theme.textTheme.titleLarge!.copyWith(color: theme.colorScheme.primaryContainer.withOpacity(1))), Text(subtitle, style: CustomTextStyles.bodySmallSecondaryContainer.copyWith(color: theme.colorScheme.secondaryContainer))]); } 
/// Navigates to the homeSettingsScreen when the action is triggered.
onTapBtnMenu() { Get.toNamed(AppRoutes.homeSettingsScreen, ); } 
/// Navigates to the categoryOneScreen when the action is triggered.
onTapBtnArrowDown() { Get.toNamed(AppRoutes.categoryOneScreen, ); } 
 }
