import 'controller/card_list_controller.dart';import 'package:ecommerce_seller_app/core/app_export.dart';import 'package:ecommerce_seller_app/presentation/profile_page/profile_page.dart';import 'package:ecommerce_seller_app/presentation/search_package_page/search_package_page.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_title.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_trailing_iconbutton_two.dart';import 'package:ecommerce_seller_app/widgets/app_bar/custom_app_bar.dart';import 'package:ecommerce_seller_app/widgets/custom_bottom_bar.dart';import 'package:ecommerce_seller_app/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class CardListScreen extends GetWidget<CardListController> {const CardListScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 33.v), Expanded(child: SingleChildScrollView(child: _buildCardList()))])), bottomNavigationBar: _buildBottomBar())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 66.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 7.v, bottom: 7.v), onTap: () {onTapArrowDown();}), centerTitle: true, title: AppbarTitle(text: "lbl_card_list".tr), actions: [AppbarTrailingIconbuttonTwo(imagePath: ImageConstant.imgFrameWhiteA700, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 12.v), onTap: () {onTapIconButton();})]); } 
/// Section Widget
Widget _buildCardList() { return Padding(padding: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 5.v), child: Column(children: [Container(padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 13.v), decoration: AppDecoration.fillBlue50.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 7.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgImage17, height: 15.v, width: 21.h, margin: EdgeInsets.symmetric(vertical: 4.v)), CustomImageView(imagePath: ImageConstant.imgFrameBlueGray900, height: 24.adaptSize, width: 24.adaptSize)])), SizedBox(height: 7.v), Padding(padding: EdgeInsets.only(left: 7.h), child: Text("msg_acc_number_230_523".tr, style: CustomTextStyles.bodyMediumGray900)), SizedBox(height: 11.v), Padding(padding: EdgeInsets.only(left: 7.h), child: Text("msg_acc_type_corporate".tr, style: CustomTextStyles.bodyMediumGray900)), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(left: 7.h), child: Text("msg_balance_5000_00".tr, style: CustomTextStyles.titleSmallRed300)), SizedBox(height: 8.v)])), SizedBox(height: 20.v), CustomElevatedButton(height: 50.v, text: "msg_852_159".tr, rightIcon: Container(margin: EdgeInsets.only(left: 30.h), child: CustomImageView(imagePath: ImageConstant.imgFrameBlueGray900, height: 24.adaptSize, width: 24.adaptSize)), leftIcon: Container(margin: EdgeInsets.only(right: 30.h), child: CustomImageView(imagePath: ImageConstant.imgImage18, height: 18.adaptSize, width: 18.adaptSize)), buttonStyle: CustomButtonStyles.fillBlueTL6, buttonTextStyle: CustomTextStyles.bodyMediumGray900)])); } 
/// Section Widget
Widget _buildBottomBar() { return CustomBottomBar(onChanged: (BottomBarEnum type) {Get.toNamed(getCurrentRoute(type), id: 1);}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Add11: return AppRoutes.searchPackagePage; case BottomBarEnum.Add2: return "/"; case BottomBarEnum.Checklist2: return "/"; case BottomBarEnum.Search: return "/"; case BottomBarEnum.Framebluegray4000220x20: return AppRoutes.profilePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.searchPackagePage: return SearchPackagePage(); case AppRoutes.profilePage: return ProfilePage(); default: return DefaultWidget();} } 
/// Navigates to the addCardBlankOneScreen when the action is triggered.
onTapArrowDown() { Get.toNamed(AppRoutes.addCardBlankOneScreen, ); } 
/// Navigates to the addCardBlankOneScreen when the action is triggered.
onTapIconButton() { Get.toNamed(AppRoutes.addCardBlankOneScreen, ); } 
 }
