import 'controller/order_filter_controller.dart';import 'package:ecommerce_seller_app/core/app_export.dart';import 'package:ecommerce_seller_app/presentation/profile_page/profile_page.dart';import 'package:ecommerce_seller_app/presentation/search_package_page/search_package_page.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_leading_iconbutton_two.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_title.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_trailing_iconbutton_one.dart';import 'package:ecommerce_seller_app/widgets/app_bar/custom_app_bar.dart';import 'package:ecommerce_seller_app/widgets/custom_bottom_bar.dart';import 'package:ecommerce_seller_app/widgets/custom_checkbox_button.dart';import 'package:flutter/material.dart';class OrderFilterScreen extends GetWidget<OrderFilterController> {const OrderFilterScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 16.v), _buildEightyTwo(), Spacer()])), bottomNavigationBar: _buildBottomBar())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 57.h, leading: AppbarLeadingIconbuttonTwo(imagePath: ImageConstant.imgFilter1, margin: EdgeInsets.only(left: 25.h, top: 12.v, bottom: 12.v)), centerTitle: true, title: AppbarTitle(text: "lbl_selling_record".tr), actions: [AppbarTrailingIconbuttonOne(imagePath: ImageConstant.imgCalendar1, margin: EdgeInsets.symmetric(horizontal: 21.h, vertical: 12.v), onTap: () {onTapCalendarOne();})]); } 
/// Section Widget
Widget _buildEightyTwo() { return Container(padding: EdgeInsets.symmetric(horizontal: 25.h, vertical: 22.v), decoration: AppDecoration.outlineBlack.copyWith(borderRadius: BorderRadiusStyle.customBorderBL38), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(bottom: 6.v), padding: EdgeInsets.symmetric(horizontal: 3.h, vertical: 5.v), decoration: AppDecoration.fillGreenA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder2), child: CustomImageView(imagePath: ImageConstant.imgVector, height: 5.v, width: 7.h, alignment: Alignment.centerRight)), Padding(padding: EdgeInsets.only(left: 10.h), child: Text("lbl_completed".tr, style: theme.textTheme.titleMedium)), Spacer(), Padding(padding: EdgeInsets.only(bottom: 5.v), child: Text("lbl_2000_items".tr, style: CustomTextStyles.bodySmallSecondaryContainer))]), SizedBox(height: 12.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Obx(() => CustomCheckboxButton(text: "lbl_cancel".tr, value: controller.cancel.value, onChange: (value) {controller.cancel.value = value;})), Padding(padding: EdgeInsets.only(top: 2.v, bottom: 3.v), child: Text("lbl_2000_items".tr, style: CustomTextStyles.bodySmallSecondaryContainer))]), SizedBox(height: 4.v)])); } 
/// Section Widget
Widget _buildBottomBar() { return CustomBottomBar(onChanged: (BottomBarEnum type) {Get.toNamed(getCurrentRoute(type), id: 1);}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Add11: return AppRoutes.searchPackagePage; case BottomBarEnum.Add2: return "/"; case BottomBarEnum.Checklist2: return "/"; case BottomBarEnum.Search: return "/"; case BottomBarEnum.Framebluegray4000220x20: return AppRoutes.profilePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.searchPackagePage: return SearchPackagePage(); case AppRoutes.profilePage: return ProfilePage(); default: return DefaultWidget();} } 
/// Navigates to the dateFilterTabContainerScreen when the action is triggered.
onTapCalendarOne() { Get.toNamed(AppRoutes.dateFilterTabContainerScreen, ); } 
 }
