import '../notification_screen/widgets/paymentnotification_item_widget.dart';import '../notification_screen/widgets/paymentnotificationlist_item_widget.dart';import 'controller/notification_controller.dart';import 'models/paymentnotification_item_model.dart';import 'models/paymentnotificationlist_item_model.dart';import 'package:ecommerce_seller_app/core/app_export.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_title.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:ecommerce_seller_app/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class NotificationScreen extends GetWidget<NotificationController> {const NotificationScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 22.h, vertical: 20.v), child: Column(children: [SizedBox(height: 7.v), _buildPaymentNotificationList(), SizedBox(height: 8.v), _buildEarlierColumn()])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 66.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 7.v, bottom: 7.v), onTap: () {onTapArrowDown();}), centerTitle: true, title: AppbarTitle(text: "lbl_notifications".tr), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgNotification, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 7.v))]); } 
/// Section Widget
Widget _buildPaymentNotificationList() { return Padding(padding: EdgeInsets.only(right: 4.h), child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return Padding(padding: EdgeInsets.symmetric(vertical: 3.5.v), child: SizedBox(width: 327.h, child: Divider(height: 1.v, thickness: 1.v, color: appTheme.blue50B5)));}, itemCount: controller.notificationModelObj.value.paymentnotificationlistItemList.value.length, itemBuilder: (context, index) {PaymentnotificationlistItemModel model = controller.notificationModelObj.value.paymentnotificationlistItemList.value[index]; return PaymentnotificationlistItemWidget(model);}))); } 
/// Section Widget
Widget _buildEarlierColumn() { return Padding(padding: EdgeInsets.only(right: 4.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_earlier".tr, style: theme.textTheme.titleMedium), SizedBox(height: 9.v), Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return Padding(padding: EdgeInsets.symmetric(vertical: 4.0.v), child: SizedBox(width: 327.h, child: Divider(height: 1.v, thickness: 1.v, color: appTheme.blue50B5)));}, itemCount: controller.notificationModelObj.value.paymentnotificationItemList.value.length, itemBuilder: (context, index) {PaymentnotificationItemModel model = controller.notificationModelObj.value.paymentnotificationItemList.value[index]; return PaymentnotificationItemWidget(model);}))])); } 
/// Navigates to the homeSettingsScreen when the action is triggered.
onTapArrowDown() { Get.toNamed(AppRoutes.homeSettingsScreen, ); } 
 }
