import 'controller/verification_controller.dart';import 'package:ecommerce_seller_app/core/app_export.dart';import 'package:ecommerce_seller_app/presentation/profile_page/profile_page.dart';import 'package:ecommerce_seller_app/presentation/search_package_page/search_package_page.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_title.dart';import 'package:ecommerce_seller_app/widgets/app_bar/custom_app_bar.dart';import 'package:ecommerce_seller_app/widgets/custom_bottom_bar.dart';import 'package:ecommerce_seller_app/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';class VerificationScreen extends GetWidget<VerificationController> {const VerificationScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 35.v), child: Column(children: [SizedBox(width: 249.h, child: RichText(text: TextSpan(children: [TextSpan(text: "msg_thank_you_for_sign2".tr, style: CustomTextStyles.titleLargeBlack900SemiBold), TextSpan(text: "lbl_abc_com".tr, style: CustomTextStyles.titleLargePrimary)]), textAlign: TextAlign.center)), SizedBox(height: 55.v), SizedBox(width: 235.h, child: Text("msg_please_select_your".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyLargePrimaryContainer16)), SizedBox(height: 30.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomIconButton(height: 50.adaptSize, width: 50.adaptSize, padding: EdgeInsets.all(10.h), decoration: IconButtonStyleHelper.outlineBlueGray, child: CustomImageView(imagePath: ImageConstant.imgLogosGoogleGmail)), GestureDetector(onTap: () {onTapCall();}, child: Container(height: 50.adaptSize, width: 50.adaptSize, margin: EdgeInsets.only(left: 20.h), padding: EdgeInsets.all(10.h), decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: CustomIconButton(height: 30.adaptSize, width: 30.adaptSize, padding: EdgeInsets.all(2.h), decoration: IconButtonStyleHelper.fillPrimaryContainer, alignment: Alignment.center, child: CustomImageView(imagePath: ImageConstant.imgCall)))), Padding(padding: EdgeInsets.only(left: 20.h), child: CustomIconButton(height: 50.adaptSize, width: 50.adaptSize, padding: EdgeInsets.all(10.h), decoration: IconButtonStyleHelper.outlineBlueGray, child: CustomImageView(imagePath: ImageConstant.imgChatBubble1)))]), SizedBox(height: 5.v)])), bottomNavigationBar: _buildBottomBar())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 66.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 7.v, bottom: 7.v)), centerTitle: true, title: AppbarTitle(text: "lbl_verification".tr)); } 
/// Section Widget
Widget _buildBottomBar() { return CustomBottomBar(onChanged: (BottomBarEnum type) {Get.toNamed(getCurrentRoute(type), id: 1);}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Add11: return AppRoutes.searchPackagePage; case BottomBarEnum.Add2: return "/"; case BottomBarEnum.Checklist2: return "/"; case BottomBarEnum.Search: return "/"; case BottomBarEnum.Framebluegray4000220x20: return AppRoutes.profilePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.searchPackagePage: return SearchPackagePage(); case AppRoutes.profilePage: return ProfilePage(); default: return DefaultWidget();} } 
/// Navigates to the verificationOneScreen when the action is triggered.
onTapCall() { Get.toNamed(AppRoutes.verificationOneScreen, ); } 
 }
