import 'controller/order_filter_one_controller.dart';import 'package:ecommerce_seller_app/core/app_export.dart';import 'package:ecommerce_seller_app/presentation/profile_page/profile_page.dart';import 'package:ecommerce_seller_app/presentation/search_package_page/search_package_page.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_title.dart';import 'package:ecommerce_seller_app/widgets/app_bar/custom_app_bar.dart';import 'package:ecommerce_seller_app/widgets/custom_bottom_bar.dart';import 'package:ecommerce_seller_app/widgets/custom_checkbox_button.dart';import 'package:ecommerce_seller_app/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';class OrderFilterOneScreen extends GetWidget<OrderFilterOneController> {const OrderFilterOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 11.v), child: Column(children: [_buildFilterOne(), SizedBox(height: 28.v), _buildOrderInProgress(), SizedBox(height: 5.v)])), bottomNavigationBar: _buildBottomBar())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 61.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 19.h, top: 7.v, bottom: 7.v), onTap: () {onTapArrowDown();}), centerTitle: true, title: AppbarTitle(text: "lbl_order_details2".tr)); } 
/// Section Widget
Widget _buildFilterOne() { return Padding(padding: EdgeInsets.only(left: 25.h, right: 21.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(7.h), decoration: IconButtonStyleHelper.fillPrimaryContainerTL10, child: CustomImageView(imagePath: ImageConstant.imgFilter1)), CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(7.h), decoration: IconButtonStyleHelper.outlinePrimaryContainer, child: CustomImageView(imagePath: ImageConstant.imgCalendar1))])); } 
/// Section Widget
Widget _buildOrderInProgress() { return Container(padding: EdgeInsets.symmetric(horizontal: 25.h, vertical: 21.v), decoration: AppDecoration.outlineBlack.copyWith(borderRadius: BorderRadiusStyle.customBorderTL40), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(top: 2.v, bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 3.h, vertical: 5.v), decoration: AppDecoration.fillGreenA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder2), child: CustomImageView(imagePath: ImageConstant.imgVector, height: 5.v, width: 7.h, alignment: Alignment.centerRight)), Padding(padding: EdgeInsets.only(left: 10.h), child: Text("lbl_in_queue".tr, style: theme.textTheme.titleMedium)), Spacer(), Padding(padding: EdgeInsets.only(bottom: 4.v), child: Text("lbl_2000_items".tr, style: CustomTextStyles.bodySmallSecondaryContainer))]), SizedBox(height: 16.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Obx(() => CustomCheckboxButton(text: "lbl_in_progress".tr, value: controller.inProgress.value, onChange: (value) {controller.inProgress.value = value;})), Padding(padding: EdgeInsets.only(bottom: 5.v), child: Text("lbl_2000_items".tr, style: CustomTextStyles.bodySmallSecondaryContainer))]), SizedBox(height: 14.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Obx(() => CustomCheckboxButton(text: "lbl_completed".tr, value: controller.completed.value, onChange: (value) {controller.completed.value = value;})), Padding(padding: EdgeInsets.only(bottom: 5.v), child: Text("lbl_2000_items".tr, style: CustomTextStyles.bodySmallSecondaryContainer))]), SizedBox(height: 4.v)])); } 
/// Section Widget
Widget _buildBottomBar() { return CustomBottomBar(onChanged: (BottomBarEnum type) {Get.toNamed(getCurrentRoute(type), id: 1);}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Add11: return AppRoutes.searchPackagePage; case BottomBarEnum.Add2: return "/"; case BottomBarEnum.Checklist2: return "/"; case BottomBarEnum.Search: return "/"; case BottomBarEnum.Framebluegray4000220x20: return AppRoutes.profilePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.searchPackagePage: return SearchPackagePage(); case AppRoutes.profilePage: return ProfilePage(); default: return DefaultWidget();} } 
/// Navigates to the orderDetailsScreen when the action is triggered.
onTapArrowDown() { Get.toNamed(AppRoutes.orderDetailsScreen, ); } 
 }
