import '../search_package_page/widgets/orderdetailslist_item_widget.dart';import 'controller/search_package_controller.dart';import 'models/orderdetailslist_item_model.dart';import 'models/search_package_model.dart';import 'package:ecommerce_seller_app/core/app_export.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_title_searchview.dart';import 'package:ecommerce_seller_app/widgets/app_bar/custom_app_bar.dart';import 'package:ecommerce_seller_app/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class SearchPackagePage extends StatelessWidget {SearchPackagePage({Key? key}) : super(key: key);

SearchPackageController controller = Get.put(SearchPackageController(SearchPackageModel().obs));

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 11.v), child: Column(children: [Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [CustomIconButton(height: 20.adaptSize, width: 20.adaptSize, padding: EdgeInsets.all(4.h), decoration: IconButtonStyleHelper.fillGray, onTap: () {onTapBtnIconButton();}, child: CustomImageView(imagePath: ImageConstant.imgFrameGray900)), Padding(padding: EdgeInsets.only(left: 10.h), child: CustomIconButton(height: 20.adaptSize, width: 20.adaptSize, child: CustomImageView(imagePath: ImageConstant.imgMenuGray60001)))]))), SizedBox(height: 11.v), SizedBox(height: 840.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [_buildOrderDetails(), _buildOrderDetailsList()])), SizedBox(height: 14.v), _buildOrderIDAAVColumn(), SizedBox(height: 4.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("lbl_50_00".tr, style: CustomTextStyles.titleSmallRed300)))]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 66.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 7.v, bottom: 7.v), onTap: () {onTapArrowDown();}), title: AppbarTitleSearchview(margin: EdgeInsets.only(left: 13.h), hintText: "msg_search_package_for".tr, controller: controller.searchController)); } 
/// Section Widget
Widget _buildOrderDetails() { return Align(alignment: Alignment.bottomCenter, child: Container(margin: EdgeInsets.only(bottom: 120.v), padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 6.v), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 7.v), _buildFrame(orderId: "msg_order_id_aa4587v".tr), SizedBox(height: 9.v), Text("msg_electric_package".tr, style: CustomTextStyles.titleSmallGray900), SizedBox(height: 2.v), RichText(text: TextSpan(children: [TextSpan(text: "lbl_address".tr, style: CustomTextStyles.bodySmall11), TextSpan(text: "msg_42_5_malibagh_moor".tr, style: CustomTextStyles.bodySmallGray60001)]), textAlign: TextAlign.left), SizedBox(height: 4.v), Text("lbl_50_00".tr, style: CustomTextStyles.titleSmallRed300)]))); } 
/// Section Widget
Widget _buildOrderDetailsList() { return Align(alignment: Alignment.center, child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 1.v);}, itemCount: controller.searchPackageModelObj.value.orderdetailslistItemList.value.length, itemBuilder: (context, index) {OrderdetailslistItemModel model = controller.searchPackageModelObj.value.orderdetailslistItemList.value[index]; return OrderdetailslistItemWidget(model, onTapBtnEditButton: () {onTapBtnEditButton();});}))); } 
/// Section Widget
Widget _buildOrderIDAAVColumn() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildFrame(orderId: "msg_order_id_aa4587v".tr), SizedBox(height: 9.v), Text("msg_electric_package".tr, style: CustomTextStyles.titleSmallGray900), SizedBox(height: 2.v), RichText(text: TextSpan(children: [TextSpan(text: "lbl_address".tr, style: CustomTextStyles.bodySmall11), TextSpan(text: "msg_42_5_malibagh_moor".tr, style: CustomTextStyles.bodySmallGray60001)]), textAlign: TextAlign.left)])); } 
/// Common widget
Widget _buildFrame({required String orderId}) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.symmetric(vertical: 1.v), child: Text(orderId, style: CustomTextStyles.titleSmallGray40001.copyWith(color: appTheme.gray40001))), CustomIconButton(height: 24.adaptSize, width: 24.adaptSize, padding: EdgeInsets.all(4.h), decoration: IconButtonStyleHelper.fillPrimary, child: CustomImageView(imagePath: ImageConstant.imgMynauiEditWhiteA700))]); } 
/// Navigates to the createPackageScreen when the action is triggered.
onTapArrowDown() { Get.toNamed(AppRoutes.createPackageScreen); } 
/// Navigates to the searchPackageOneScreen when the action is triggered.
onTapBtnIconButton() { Get.toNamed(AppRoutes.searchPackageOneScreen); } 
/// Navigates to the productPublishOneScreen when the action is triggered.
onTapBtnEditButton() { Get.toNamed(AppRoutes.productPublishOneScreen, ); } 
 }
