import '../order_details_screen/widgets/orderdetailslist1_item_widget.dart';import 'controller/order_details_controller.dart';import 'models/orderdetailslist1_item_model.dart';import 'package:ecommerce_seller_app/core/app_export.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:ecommerce_seller_app/widgets/app_bar/appbar_title.dart';import 'package:ecommerce_seller_app/widgets/app_bar/custom_app_bar.dart';import 'package:ecommerce_seller_app/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';class OrderDetailsScreen extends GetWidget<OrderDetailsController> {const OrderDetailsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 22.h, vertical: 11.v), child: Column(children: [_buildFilterOne(), SizedBox(height: 18.v), _buildOrderDetailsList()])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 61.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 19.h, top: 7.v, bottom: 7.v), onTap: () {onTapArrowDown();}), centerTitle: true, title: AppbarTitle(text: "lbl_order_details2".tr)); } 
/// Section Widget
Widget _buildFilterOne() { return Padding(padding: EdgeInsets.only(left: 2.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(7.h), decoration: IconButtonStyleHelper.fillPrimaryContainerTL10, onTap: () {onTapBtnFilterOne();}, child: CustomImageView(imagePath: ImageConstant.imgFilter1)), CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(7.h), decoration: IconButtonStyleHelper.outlinePrimaryContainer, child: CustomImageView(imagePath: ImageConstant.imgCalendar1))])); } 
/// Section Widget
Widget _buildOrderDetailsList() { return Expanded(child: Padding(padding: EdgeInsets.only(left: 2.h), child: Obx(() => ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return Padding(padding: EdgeInsets.symmetric(vertical: 5.0.v), child: SizedBox(width: 327.h, child: Divider(height: 1.v, thickness: 1.v, color: appTheme.gray30002)));}, itemCount: controller.orderDetailsModelObj.value.orderdetailslist1ItemList.value.length, itemBuilder: (context, index) {Orderdetailslist1ItemModel model = controller.orderDetailsModelObj.value.orderdetailslist1ItemList.value[index]; return Orderdetailslist1ItemWidget(model);})))); } 
/// Navigates to the homeSettingsScreen when the action is triggered.
onTapArrowDown() { Get.toNamed(AppRoutes.homeSettingsScreen, ); } 
/// Navigates to the orderFilterOneScreen when the action is triggered.
onTapBtnFilterOne() { Get.toNamed(AppRoutes.orderFilterOneScreen, ); } 
 }
